jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.0
        auth:
          username: fivebird
          password: $DOCKER_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: docker build -t fivebird/circletest .
  push:
    docker:
      - image: cimg/openjdk:17.0.0
        auth:
          username: fivebird
          password: $DOCKER_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: sudo docker push fivebird/circletest:latest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - push
